DROP TABLE GENRE;

DROP TABLE MOVIE;

DROP TABLE FAVORITE_LIST;

CREATE TABLE GENRE (
    ID INT NOT NULL, 
    NAME VARCHAR(20) NOT NULL, 
    PRIMARY KEY(ID)
);

CREATE TABLE MOVIE(
    ID INT NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    RELEASE_DATE DATE,
    RATING FLOAT(10) NOT NULL,
    OVERVIEW VARCHAR(500),
    GENRE_ID INT,
    FAVORITE_LIST_ID INT,
    PRIMARY KEY(ID) 
);

CREATE TABLE FAVORITE_LIST (
    ID INT NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    PRIMARY KEY(ID)
);

ALTER TABLE MOVIE ADD FOREIGN KEY (GENRE_ID) REFERENCES GENRE;

ALTER TABLE MOVIE ADD FOREIGN KEY (FAVORITE_LIST_ID) REFERENCES FAVORITE_LIST;