/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.UIManager;
import managers.DbManager;
import messages.Captions;

/**
 *
 * @author Niobe
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    class TaskInitialize extends SwingWorker<Void, Void> {

        @Override
        protected Void doInBackground() throws Exception {
            DbManager.initializeDb();
            return null;
        }

        @Override
        protected void done() {
            progressInitialize.setVisible(false);
            dialogInitialize.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogInitialize = new javax.swing.JDialog();
        progressInitialize = new javax.swing.JProgressBar();
        labelInitialize = new javax.swing.JLabel();
        buttonInitialize = new javax.swing.JButton();
        buttonCancelInitialize = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuInitialize = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuExit = new javax.swing.JMenuItem();

        dialogInitialize.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogInitialize.setTitle("Ανάκτηση και Αποθήκευση Δεδομένων");
        dialogInitialize.setAlwaysOnTop(true);
        dialogInitialize.setModal(true);
        dialogInitialize.setUndecorated(true);
        dialogInitialize.setResizable(false);
        dialogInitialize.setSize(new java.awt.Dimension(600, 400));

        progressInitialize.setFocusable(false);
        progressInitialize.setIndeterminate(true);

        labelInitialize.setText("Επιθυμείτε να γίνει Ανάκτηση και Αποθήκευση Δεδομένων Ταινιών;");

        buttonInitialize.setText("Αρχικοποίηση");
        buttonInitialize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInitializeActionPerformed(evt);
            }
        });

        buttonCancelInitialize.setText("Άκυρο");
        buttonCancelInitialize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelInitializeActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("sansserif", 2, 12)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(3);
        jTextArea1.setText("Προσοχή: \nΜε την αρχικοποίηση θα γίνει διαγραφή της Βάσης Δεδομένων\nκαι θα χαθούν οριστικά οι Λίστες Αγαπημένων Ταινιών!");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout dialogInitializeLayout = new javax.swing.GroupLayout(dialogInitialize.getContentPane());
        dialogInitialize.getContentPane().setLayout(dialogInitializeLayout);
        dialogInitializeLayout.setHorizontalGroup(
            dialogInitializeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogInitializeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogInitializeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelInitialize, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addComponent(progressInitialize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dialogInitializeLayout.createSequentialGroup()
                        .addComponent(buttonInitialize, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonCancelInitialize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogInitializeLayout.setVerticalGroup(
            dialogInitializeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogInitializeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelInitialize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressInitialize, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogInitializeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonInitialize)
                    .addComponent(buttonCancelInitialize))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyMovies");
        setSize(new java.awt.Dimension(600, 400));

        jDesktopPane1.setAutoscrolls(true);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 997, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
        );

        jMenu1.setText("Αρχείο");

        menuInitialize.setText("Ανάκτηση και Αποθήκευση Δεδομένων Ταινιών");
        menuInitialize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInitializeActionPerformed(evt);
            }
        });
        jMenu1.add(menuInitialize);
        jMenu1.add(jSeparator1);

        menuExit.setText("Έξοδος");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuInitializeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInitializeActionPerformed
        //dialogInitialize.setTitle(Captions.DIALOG_INITIALIZE_TITLE);
        //labelInitialize.setText(Captions.DIALOG_INITIALIZE_LABEL_INFO);

        progressInitialize.setVisible(false);
        dialogInitialize.pack();
        dialogInitialize.setLocationRelativeTo(this);

        dialogInitialize.setVisible(true);
    }//GEN-LAST:event_menuInitializeActionPerformed

    private void buttonInitializeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInitializeActionPerformed

        progressInitialize.setVisible(true);
        new TaskInitialize().execute();

    }//GEN-LAST:event_buttonInitializeActionPerformed

    private void buttonCancelInitializeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelInitializeActionPerformed
        dialogInitialize.setVisible(false);
    }//GEN-LAST:event_buttonCancelInitializeActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menuExitActionPerformed

    public static void main(String args[]) {
        UIManager.put("control", new Color(128, 128, 128));
        UIManager.put("info", new Color(128, 128, 128));
        UIManager.put("nimbusBase", new Color(18, 30, 49));
        UIManager.put("nimbusAlertYellow", new Color(248, 187, 0));
        UIManager.put("nimbusDisabledText", new Color(128, 128, 128));
        UIManager.put("nimbusFocus", new Color(115, 164, 209));
        UIManager.put("nimbusGreen", new Color(176, 179, 50));
        UIManager.put("nimbusInfoBlue", new Color(66, 139, 221));
        UIManager.put("nimbusLightBackground", new Color(18, 30, 49));
        UIManager.put("nimbusOrange", new Color(191, 98, 4));
        UIManager.put("nimbusRed", new Color(169, 46, 34));
        UIManager.put("nimbusSelectedText", new Color(255, 255, 255));
        UIManager.put("nimbusSelectionBackground", new Color(104, 93, 156));
        UIManager.put("text", new Color(230, 230, 230));

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new MainForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelInitialize;
    private javax.swing.JButton buttonInitialize;
    private javax.swing.JDialog dialogInitialize;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelInitialize;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuInitialize;
    private javax.swing.JProgressBar progressInitialize;
    // End of variables declaration//GEN-END:variables
}
