CREATE TABLE GENRE (ID INTEGER NOT NULL,NAME VARCHAR(20) NOT NULL,PRIMARY KEY(ID))

CREATE TABLE MOVIE(ID INTEGER NOT NULL,TITLE VARCHAR(100) NOT NULL,RELEASE_DATE DATE,RATING FLOAT(10) NOT NULL,OVERVIEW VARCHAR(500),GENRE_ID INTEGER,FAVORITE_LIST_ID INTEGER,PRIMARY KEY(ID) )

CREATE TABLE FAVORITE_LIST (ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),NAME VARCHAR(50) NOT NULL,PRIMARY KEY(ID))

ALTER TABLE MOVIE ADD FOREIGN KEY (GENRE_ID) REFERENCES GENRE

ALTER TABLE MOVIE ADD FOREIGN KEY (FAVORITE_LIST_ID) REFERENCES FAVORITE_LIST